version: '3.1'
services:
  db:
    image: mysql:5.7.44
    volumes:
        - ./initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      TZ: "Asia/Tokyo"
      COMPOSE_PROJECT_NAME: myapp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
